# Generated by Django 4.2.3 on 2023-07-07 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m7app', '0002_etiqueta_tarea_delete_post_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
