# Generated by Django 4.2.3 on 2023-07-08 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m7app', '0008_alter_prioridad_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='prioridad',
            field=models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Prioridad',
        ),
    ]
