# Generated by Django 4.2.3 on 2023-07-09 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m7app', '0009_alter_tarea_prioridad_delete_prioridad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prioridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
    ]
